version: 2
jobs:
  build:
    docker:
      - image: mono

    steps:
      - checkout

      - run:
          name: Build
          command: xbuild EngineGL.sln

      - run:
          name: Test
          command: date