version: 2
jobs:
  build:
    docker:
      - image: mono

    steps:
      - checkout

      - restore_cache:
          keys:
            - nuget-v1-{{ checksum "EngineGL/EngineGL/packages.config" }}-{{ checksum "EngineGL/EngineGL.Editor/packages.config" }}-{{ checksum "EngineGL/EngineGL.Tests/packages.config" }}
            - nuget-v1-{{ checksum "EngineGL/EngineGL/packages.config" }}-{{ checksum "EngineGL/EngineGL.Editor/packages.config" }}-
            - nuget-v1-{{ checksum "EngineGL/EngineGL/packages.config" }}-
            - nuget-v1-

      - run:
          name: Nuget Restore
          command: nuget restore

      - save_cache:
          key: nuget-v1-{{ checksum "EngineGL/EngineGL/packages.config" }}-{{ checksum "EngineGL/EngineGL.Editor/packages.config" }}-{{ checksum "EngineGL/EngineGL.Tests/packages.config" }}
          paths:
            - "packages"

      - run:
          name: Build
          command: xbuild EngineGL.sln

      - run:
          name: Test
          command: date