version: 2
jobs:
  build:
    docker:
      - image: mono

    steps:
      - checkout

      - restore_cache:
          keys:
            - nuget-v1-{{ checksum "EngineGL/packages.config" }}-{{ checksum "EngineGL.Editor/packages.config" }}-{{ checksum "EngineGL.Tests/packages.config" }}
            - nuget-v1-{{ checksum "EngineGL/packages.config" }}-{{ checksum "EngineGL.Editor/packages.config" }}-
            - nuget-v1-{{ checksum "EngineGL/packages.config" }}-
            - nuget-v1-

      - run:
          name: Nuget Restore
          command: nuget restore

      - save_cache:
          key: nuget-v1-{{ checksum "EngineGL/packages.config" }}-{{ checksum "EngineGL.Editor/packages.config" }}-{{ checksum "EngineGL.Tests/packages.config" }}
          paths:
            - "packages"

      - run:
          name: Build
          command: xbuild EngineGL.sln

      - run:
          name: Test
          command: mono "packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe" "EngineGL.CITests/bin/Debug/EngineGL.CITests.dll"
